name: moltaqa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.5
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0
  badges: ^2.0.2
  carousel_slider: ^4.0.0
  image_stack: ^2.1.1
  get_storage: ^2.0.3
  get: ^4.3.8
  url_launcher: ^6.1.0
  flutter_bloc: ^8.0.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_app_name: ^0.1.0

flutter_icons:
  image_path: "assets/icons/logo.png"
  android: true
  ios: true

flutter_app_name:
    name: " Moltaqa For Must University"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
#   - assets/images/